-- Real cartography: multi-part geometry, a chainage range, and influence areas (ADR-023).
--
-- Generated by drizzle-kit and then edited in one respect: PostGIS does not widen
-- `geometry(Polygon)` to `geometry(MultiPolygon)` implicitly, so each widening carries an explicit
-- `USING ST_Multi(geom)`. The cast is lossless — a polygon is a multipolygon of one part — so no
-- existing row changes meaning and none is rewritten in substance.
--
-- Forward only. Nothing is dropped and nothing is deleted.

CREATE TYPE "app"."influence_area_kind" AS ENUM('direct', 'indirect', 'direct_social', 'indirect_social');--> statement-breakpoint
ALTER TYPE "app"."spatial_dataset_kind" ADD VALUE 'influence_areas';--> statement-breakpoint
CREATE TABLE "app"."influence_area" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"dataset_version_id" uuid NOT NULL,
	"kind" "app"."influence_area_kind" NOT NULL,
	"label" text NOT NULL,
	"geom" geometry(MultiPolygon,4326) NOT NULL,
	"area_m2" numeric(16, 2) NOT NULL,
	"provenance_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "influence_area_version_kind_key" UNIQUE("tenant_id","dataset_version_id","kind"),
	CONSTRAINT "influence_area_tenant_id_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
ALTER TABLE "app"."affectation" ALTER COLUMN "geom" SET DATA TYPE geometry(MultiPolygon,4326) USING ST_Multi("geom");--> statement-breakpoint
ALTER TABLE "app"."alignment" ALTER COLUMN "geom" SET DATA TYPE geometry(MultiLineString,4326) USING ST_Multi("geom");--> statement-breakpoint
ALTER TABLE "app"."parcel_geometry" ALTER COLUMN "geom" SET DATA TYPE geometry(MultiPolygon,4326) USING ST_Multi("geom");--> statement-breakpoint
ALTER TABLE "app"."parcel" ADD COLUMN "chainage_start_m" numeric(10, 1);--> statement-breakpoint
ALTER TABLE "app"."parcel" ADD COLUMN "chainage_end_m" numeric(10, 1);--> statement-breakpoint
ALTER TABLE "app"."influence_area" ADD CONSTRAINT "influence_area_version_fk" FOREIGN KEY ("tenant_id","dataset_version_id") REFERENCES "app"."spatial_dataset_version"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."influence_area" ADD CONSTRAINT "influence_area_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "app"."project"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."influence_area" ADD CONSTRAINT "influence_area_provenance_fk" FOREIGN KEY ("tenant_id","provenance_id") REFERENCES "app"."provenance_record"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "influence_area_geom_idx" ON "app"."influence_area" USING gist ("geom");