-- Field media (Production V1 Wave 2, ADR-032).
--
-- Generated by drizzle-kit from the schema, so the snapshot and the migrations stay in agreement
-- (the drift check in CI is what keeps them so). The table's *rules* are in the schema's docblock
-- and in `packages/domain/src/field/media.ts`; what is here is shape.
--
-- Two unique constraints carry the no-duplicate guarantee, and they are the point of the table:
-- `field_media_local_key` on (tenant, visit, local_id) — the id the device minted at the shutter,
-- so a retry after a lost response is one photograph — and `field_media_object_key`, so the same
-- verified bytes cannot arrive as a second row by another door.
--
-- `ALTER TYPE … ADD VALUE` appends `media.declare` to the sync command vocabulary. The value is
-- not *used* in this migration, which is what PostgreSQL requires of a value added in the same
-- transaction.
--
-- Additive and forward-only: one new enum, one new value on an existing enum, one new table. No
-- row changes, no backfill, nothing dropped. Grants, FORCE RLS and the policies are 0041.

CREATE TYPE "app"."field_media_kind" AS ENUM('parcel', 'affectation', 'access', 'other');--> statement-breakpoint
ALTER TYPE "app"."field_sync_command_type" ADD VALUE 'media.declare';--> statement-breakpoint
CREATE TABLE "app"."field_media" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"visit_id" uuid NOT NULL,
	"assignment_id" uuid NOT NULL,
	"captured_by_user_id" uuid NOT NULL,
	"local_id" uuid NOT NULL,
	"stored_object_id" uuid NOT NULL,
	"kind" "app"."field_media_kind" NOT NULL,
	"captured_at" timestamp with time zone NOT NULL,
	"note" text,
	"location" geometry(Point,4326),
	"location_accuracy_m" numeric(10, 1),
	"provenance_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "field_media_tenant_id_id_key" UNIQUE("tenant_id","id"),
	CONSTRAINT "field_media_local_key" UNIQUE("tenant_id","visit_id","local_id"),
	CONSTRAINT "field_media_object_key" UNIQUE("tenant_id","stored_object_id")
);
--> statement-breakpoint
ALTER TABLE "app"."field_media" ADD CONSTRAINT "field_media_visit_fk" FOREIGN KEY ("tenant_id","visit_id") REFERENCES "app"."field_visit"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."field_media" ADD CONSTRAINT "field_media_assignment_fk" FOREIGN KEY ("tenant_id","assignment_id") REFERENCES "app"."field_assignment"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."field_media" ADD CONSTRAINT "field_media_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "app"."project"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."field_media" ADD CONSTRAINT "field_media_object_fk" FOREIGN KEY ("tenant_id","stored_object_id") REFERENCES "app"."stored_object"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."field_media" ADD CONSTRAINT "field_media_provenance_fk" FOREIGN KEY ("tenant_id","provenance_id") REFERENCES "app"."provenance_record"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "field_media_visit_idx" ON "app"."field_media" USING btree ("tenant_id","visit_id");--> statement-breakpoint
CREATE INDEX "field_media_technician_idx" ON "app"."field_media" USING btree ("tenant_id","project_id","captured_by_user_id");