-- Document extraction: what a citation points at, and the queue's own columns
-- (Production V1 Wave 2, ADR-033). Generated by drizzle-kit from the schema.
--
-- `page_from` and `page_to` become **nullable**, and that is the substantive change. A PDF has
-- printed pages a reader can turn to; a DOCX does not — its pagination is computed by whatever
-- renders it, from the fonts installed and the paper size, so two readers of one file disagree
-- about what is on page 7. Numbering chunks and calling those pages would produce citations that
-- look verifiable and are not, which is the fabrication ADR-020 refused for quality evidence.
--
-- Every existing row keeps its page numbers and gets `locator_kind = 'PAGE'`, which is what it
-- already claimed. Nothing is rewritten and nothing is lost: dropping NOT NULL widens what the
-- column may hold and narrows nothing.
--
-- Additive and forward-only. The claim and release functions are 0043.

CREATE TYPE "app"."chunk_locator_kind" AS ENUM('PAGE', 'SECTION');--> statement-breakpoint
ALTER TABLE "app"."document_chunk" ALTER COLUMN "page_from" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."document_chunk" ALTER COLUMN "page_to" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."document_chunk" ADD COLUMN "locator_kind" "app"."chunk_locator_kind" DEFAULT 'PAGE' NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."document_chunk" ADD COLUMN "section_path" text;--> statement-breakpoint
ALTER TABLE "app"."document_version" ADD COLUMN "extraction_attempts" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."document_version" ADD COLUMN "extraction_claimed_at" timestamp with time zone;