-- Socializations: events, invitations and delivery attempts (Visión Ambiental, block 3, ADR-041).
--
-- Generated by drizzle-kit from `packages/db/src/schema/socializations.ts`, so the snapshot and
-- the migrations stay in agreement, with one statement added by hand — see below. The tables'
-- *rules* are in the schema's docblocks and in `packages/domain/src/field/socializations.ts`;
-- what is here is shape. Grants, FORCE RLS, the policies and the write-once trigger are 0057.
--
-- `ALTER TYPE … ADD VALUE 'socialization-evidence'` is written by hand because the alignment
-- migration 0055 absorbed it into its snapshot while carrying nothing runnable: the value must
-- actually be added to the type, and a snapshot that says it exists is not the same thing. It is
-- added and not *used* in this transaction, which is what PostgreSQL requires — the same shape
-- migration 0040 used for `media.declare`.
--
-- Additive and forward-only: three enums, one enum value, three tables. No row changes, no
-- backfill, nothing dropped.

ALTER TYPE "app"."storage_namespace" ADD VALUE 'socialization-evidence';--> statement-breakpoint
CREATE TYPE "app"."socialization_delivery_outcome" AS ENUM('DELIVERED', 'ABSENT', 'REFUSED', 'OTHER');--> statement-breakpoint
CREATE TYPE "app"."socialization_event_status" AS ENUM('DRAFT', 'SCHEDULED', 'CANCELLED', 'COMPLETED');--> statement-breakpoint
CREATE TYPE "app"."socialization_invitation_status" AS ENUM('PENDING', 'DELIVERED', 'REFUSED', 'CANCELLED');--> statement-breakpoint
CREATE TABLE "app"."socialization_delivery_attempt" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"invitation_id" uuid NOT NULL,
	"local_id" uuid NOT NULL,
	"technician_user_id" uuid NOT NULL,
	"outcome" "app"."socialization_delivery_outcome" NOT NULL,
	"occurred_at_device" timestamp with time zone NOT NULL,
	"received_at_server" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text,
	"location" geometry(Point,4326),
	"location_accuracy_m" numeric(10, 1),
	"evidence_stored_object_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "socialization_delivery_attempt_tenant_id_id_key" UNIQUE("tenant_id","id"),
	CONSTRAINT "socialization_delivery_attempt_local_key" UNIQUE("tenant_id","invitation_id","local_id")
);
--> statement-breakpoint
CREATE TABLE "app"."socialization_event" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"title" text NOT NULL,
	"purpose" text,
	"starts_at" timestamp with time zone NOT NULL,
	"timezone" text NOT NULL,
	"location_label" text NOT NULL,
	"status" "app"."socialization_event_status" DEFAULT 'DRAFT' NOT NULL,
	"cancelled_at" timestamp with time zone,
	"cancelled_reason" text,
	"created_by_user_id" uuid NOT NULL,
	"provenance_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "socialization_event_tenant_id_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "app"."socialization_invitation" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"parcel_id" uuid NOT NULL,
	"source_assignment_id" uuid,
	"source_survey_technician_user_id" uuid,
	"assignee_membership_id" uuid NOT NULL,
	"assignee_user_id" uuid NOT NULL,
	"recipient_label" text,
	"status" "app"."socialization_invitation_status" DEFAULT 'PENDING' NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"provenance_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "socialization_invitation_tenant_id_id_key" UNIQUE("tenant_id","id"),
	CONSTRAINT "socialization_invitation_event_parcel_key" UNIQUE("tenant_id","event_id","parcel_id")
);
--> statement-breakpoint
ALTER TABLE "app"."socialization_delivery_attempt" ADD CONSTRAINT "socialization_delivery_attempt_invitation_fk" FOREIGN KEY ("tenant_id","invitation_id") REFERENCES "app"."socialization_invitation"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_delivery_attempt" ADD CONSTRAINT "socialization_delivery_attempt_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "app"."project"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_delivery_attempt" ADD CONSTRAINT "socialization_delivery_attempt_evidence_fk" FOREIGN KEY ("tenant_id","evidence_stored_object_id") REFERENCES "app"."stored_object"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_delivery_attempt" ADD CONSTRAINT "socialization_delivery_attempt_technician_fk" FOREIGN KEY ("technician_user_id") REFERENCES "app"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_event" ADD CONSTRAINT "socialization_event_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "app"."project"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_event" ADD CONSTRAINT "socialization_event_provenance_fk" FOREIGN KEY ("tenant_id","provenance_id") REFERENCES "app"."provenance_record"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_event" ADD CONSTRAINT "socialization_event_created_by_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "app"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_invitation" ADD CONSTRAINT "socialization_invitation_event_fk" FOREIGN KEY ("tenant_id","event_id") REFERENCES "app"."socialization_event"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_invitation" ADD CONSTRAINT "socialization_invitation_parcel_fk" FOREIGN KEY ("tenant_id","parcel_id") REFERENCES "app"."parcel"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_invitation" ADD CONSTRAINT "socialization_invitation_assignee_fk" FOREIGN KEY ("tenant_id","assignee_membership_id") REFERENCES "app"."project_membership"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_invitation" ADD CONSTRAINT "socialization_invitation_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "app"."project"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."socialization_invitation" ADD CONSTRAINT "socialization_invitation_provenance_fk" FOREIGN KEY ("tenant_id","provenance_id") REFERENCES "app"."provenance_record"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "socialization_delivery_attempt_invitation_idx" ON "app"."socialization_delivery_attempt" USING btree ("tenant_id","invitation_id");--> statement-breakpoint
CREATE INDEX "socialization_event_project_idx" ON "app"."socialization_event" USING btree ("tenant_id","project_id","starts_at");--> statement-breakpoint
CREATE INDEX "socialization_invitation_assignee_idx" ON "app"."socialization_invitation" USING btree ("tenant_id","assignee_user_id","status");--> statement-breakpoint
CREATE INDEX "socialization_invitation_event_idx" ON "app"."socialization_invitation" USING btree ("tenant_id","event_id","status");