-- The sync receipt learns one more command (block 3, ADR-041).
--
-- Generated by drizzle-kit. Additive and forward-only: one value on an existing enum, no table,
-- no policy, no backfill. A protocol v3 device never sends this type, and an older server would
-- reject it as an unknown discriminant — which is the right answer to a device newer than the
-- server it is talking to.
--
-- The receipt is what makes a retried delivery one row rather than two at the *command* level;
-- `socialization_delivery_attempt`'s `(tenant, invitation, local_id)` unique index is what makes
-- it one row at the *record* level, independently. Two mechanisms, because a device can lose its
-- outbox and keep its records.

ALTER TYPE "app"."field_sync_command_type" ADD VALUE 'socialization.delivery.record';